swagger: '2.0'
info:
  version: '1.0.0'
  title: "[Draft] Product Service (eCom)"
  description: |
    This APIs provides article information to eCommerce application (GLASS). It is optimized for the need of the eCommerce application and as such it is not intended for use by other clients.
    
    Refer to [Product API](https://adidasproductapi.docs.apiary.io/) for a general-purpose article information API.

    ## Available Affordances
    The API affords the following top-level actions:

    - Retrieve particular article information for a particular country (site)

    ## Link relations
    A retrieved article might contains relations to other related articles also known as "product" links. Where available these articles are embeded under respective releations. 
    
    The available relations are: 

    - `colorvariant` - Article Color variants
    - `miadidas` - Related mi-adidas producs
    - `completelook` - Articles that are provided for on-model images as paired articles

produces:
  - application/hal+json      # Representation message format
  - application/problem+json  # Error message format

schemes:
  - https

securityDefinitions:
   "API Key":
     type: apiKey
     in: header
     name: Adidas-API-Key

security:
  - "API Key": []

paths:
  /:
    x-summary: eCom Product Service API

    get:
      summary: Retrieve eCom Product Service API Root 
      description: Retrieve available top-level actions of the eCom Product Service API
      responses:
        200:
          description: The root of the API
          schema:
            type: object
            allOf:
              - $ref: '#/definitions/supermodelIoAdidasApiHAL'
            example:
              _links:
                self:
                  href: /
                article:
                  href: /articles/{article_id}
                  templated: true

  /articles/{article_id}:
    x-summary: Article
    x-description: Article Information.
    parameters:
      - $ref: '#/parameters/articleId'

    get:
      summary: Retrieve Article
      description: |
        Retrieve a particular article by its id.

        | Available Filters | Parameter Location | Parameter Name(s)          |
        |-------------------|--------------------|----------------------------|
        | language          | header             | `Accept-Language`          |

      parameters:
        - $ref: '#/parameters/siteQuery'
        - $ref: '#/parameters/acceptLanguageHeader'
      
      responses:
        200:
          description: Article information
          headers:
            Content-Language:
              type: string
              default: en
              x-example: en
            Vary:
              type: string
              default: Accept-Language
              x-example: Accept-Language
          schema:
            $ref: '#/definitions/supermodelIoAdidasProductEcomArticle'

        404:
          description: The requested article wasn't found.
          headers:
            Content-Type:
              type: string
              default: application/problem+json
          schema:
            # TODO:
            $ref: '#/definitions/supermodelIoAdidasApiProblemDetail'         

#
# Parameters Definitions
#
parameters:
  # Article Id
  articleId:
    name: article_id
    in: path
    description: Id of the Article
    required: true
    type: string
    x-example: '015110'

  site:
    name: site
    in: query
    description: eCom country code denoting the desired site 
    required: true
    type: string
    x-example: 'de'    

  # adidas API guidelines: Pagination
  offset:
    name: offset
    in: query
    description: Number of results to skip from the start of the list
    required: false
    type: string
    default: '0'
    x-example: '10'

  # adidas API guidelines: Pagination
  limit:
    name: limit
    in: query
    description: The maximum number of reusults to return
    required: false
    type: string
    default: '10'
    x-example: '5'

  # adidas API guidelines: Sparse fieldset
  fields:
    name: fields
    in: query
    description: Comma-separated list of fields to include in the response
    required: false
    type: array
    items:
      type: string
    collectionFormat: csv
    x-example:
      - articleNumber
      - modelNumber

  # adidas API guidelines: Sparse fieldset
  embedded:
    name: embedded
    in: query
    description: Comma-separated list of resource (relations) to embed in the response
    required: false
    type: array
    items:
      type: string
    collectionFormat: csv
    x-example:
      - prices
      - assets

  # adidas API guidelines: Language negotiation
  acceptLanguageHeader:
    name: 'Accept-Language'
    in: header
    type: string
    default: en
    x-example: en,en-US,fr;q=0.6

# DO NOT EDIT
# This definitions section is automatically generated by supermodel.io
#
# http://supermodel.io
# https://github.com/supermodel/supermodel-cli
definitions:
  supermodelIoAdidasApiHALDefinitionsHalLinkObject:
    title: HAL Link Object
    type: object
    properties:
      href:
        type: string
      templated:
        type: boolean
      type:
        type: string
      deprecation:
        type: string
      name:
        type: string
      profile:
        type: string
      title:
        type: string
      hreflang:
        type: string
    required:
      - href
  supermodelIoAdidasApiHALDefinitionsHalCuriesLink:
    title: HAL Curies Link
    allOf:
      - type: object
        properties:
          templated:
            enum:
              - true
        required:
          - templated
      - $ref: '#/definitions/supermodelIoAdidasApiHALDefinitionsHalLinkObject'
  supermodelIoAdidasProductCatalogDefinitionsCatalogCopy:
    title: Catalog Copy
    type: object
    properties:
      acsModelName:
        type: string
      b2cCopy:
        type: string
      b2cCopyShort:
        type: string
      b2bCopy:
        type: string
      b2bCopyShort:
        type: string
      materialComposition:
        type: string
      materialConstruction:
        type: string
      bullets1:
        type: string
      bullets2:
        type: string
      bullets3:
        type: string
      bullets4:
        type: string
      bullets5:
        type: string
      bullets6:
        type: string
      bulletMaterial:
        type: string
    example:
      acsModelName: COPA MUNDIAL
      b2cCopy: >-
        De populairste voetbalschoen ooit, en terecht. De adidas Copa Mundial
        heeft een bovenwerk van rijk leer en een loopzool met dubbele dichtheid
        die al decennia lang de toon zet voor comfort en prestaties op het veld.
      b2cCopyShort: >-
        Entraîne-toi comme les pros avec ce haut de l'équipe de Belgique de
        football.
      b2bCopy: >-
        Hurricanes Training Jersey as worn by the players when training with
        dynamic retro design inspired by the original Super Jersey.Captured with
        shock blue and black colors on climalite fabric with moisture wicking
        properties.
      b2bCopyShort: >-
        Hurricanes Training Jersey as worn by the players when training with
        dynamic retro design inspired by the orginal Super jersey.
      materialComposition: 100% Organic Cotton
      materialConstruction: Single jersey
      bullets1: materiál Climalite odvádí pot a udrží tě vsuchu za všech okolností
      bullets2: Ribbet V-hals
      bullets3: Nackenband
      bullets4: >-
        Επένδυση προστασίας από τον άνεμο στο μπροστινό μέρος. Μανσέτες με
        ανοίγματα για τους αντίχειρες
      bullets5: Woven Belgium crest on chest
      bullets6: >-
        3 bandas en las mangas; logotipo de adidas serigrafiado a la derecha del
        pecho
      bulletMaterial: Maille double 100 % polyester.
  supermodelIoAdidasProductCatalogDefinitionsFeatureAndBenefit:
    title: Feature and Benefit
    type: object
    properties:
      featureAndBenefitCode:
        type: string
      businessCode:
        type: string
      shoePart:
        type: string
      featureName:
        type: string
      featureDescription:
        type: string
      logoName:
        type: string
      logoHref:
        type: string
        format: uri
    example:
      featureAndBenefitCode: '68465468'
      businessCode: BU Young Athlete
      shoePart: Upper
      featureName: Costura à maquina
      featureDescription: >-
        construction nylon/TPU pour un bon toucher de balle et une bonne
        résistance à l'usure.
      logoName: ECO_OrthoLiteLogo
      logoHref: 'http://domain.com/logo.jpeg'
  supermodelIoAdidasApiHAL:
    title: HAL
    description: >-
      JSON Hypertext Application Language. Definition of [HAL message
      format](https://tools.ietf.org/html/draft-kelly-json-hal-08)
    type: object
    properties:
      _links:
        type: object
        additionalProperties: {}
        properties:
          curies: {}
      _embedded:
        type: object
        additionalProperties: {}
  supermodelIoAdidasApiProblemDetail:
    title: Problem Details for HTTP APIs
    description: >-
      Definition of [RFC7807](https://tools.ietf.org/html/rfc7807) problem
      detail
    type: object
    properties:
      type:
        type: string
      title:
        type: string
      status:
        type: number
      detail:
        type: string
      instance:
        type: string
    required:
      - title
      - detail
  supermodelIoAdidasProductArticle:
    title: Article
    type: object
    properties:
      articleNumber:
        type: string
      modelNumber:
        type: string
      articleDescription:
        type: string
      gender:
        $ref: '#/definitions/supermodelIoAdidasProductUtilsCodeDescription'
      brand:
        $ref: '#/definitions/supermodelIoAdidasProductUtilsCodeDescription'
      productType:
        $ref: '#/definitions/supermodelIoAdidasProductUtilsCodeDescription'
      ageGroup:
        $ref: '#/definitions/supermodelIoAdidasProductUtilsCodeDescription'
      colorway:
        type: object
        properties:
          name:
            type: string
          description:
            type: string
      colors:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasProductColor'
      seasons:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasProductArticleSeason'
      skus:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasProductSKU'
      assets:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasProductAsset'
      catalog:
        $ref: '#/definitions/supermodelIoAdidasProductCatalog'
      related:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasProductArticle'
    example:
      articleNumber: '015110'
      modelNumber: '10034'
      articleDescription: COPA MUNDIAL
      gender:
        code: M
        description: MALE
      brand:
        code: '11'
        description: ADIDAS
      productType:
        code: '104'
        description: FOOTBALL SHOES (FIRM GROUND)
      ageGroup:
        code: A
        description: ADULT
      colorway:
        name: FTWR WHITE/BLACK
        description: BLABAS/GRAFIT/BLABAS
      colors:
        - {}
      seasons:
        - {}
      skus:
        - {}
      assets:
        - {}
      catalog: {}
  supermodelIoAdidasProductArticleSeason:
    title: Article Season
    description: Seasonal information about article
    type: object
    properties:
      seasonName:
        type: string
      carryOver:
        type: boolean
      retailIntroDate:
        type: string
        format: date-time
      retailExitDate:
        type: string
        format: date-time
    example:
      seasonName: FW17
      carryOver: false
      retailIntroDate: '2017-06-01'
      retailExitDate: '2017-11-30'
  supermodelIoAdidasProductAsset:
    title: Asset
    description: Digital Asset
    type: object
    properties:
      assetType:
        type: string
        enum:
          - image
          - video
          - other
      viewGroup:
        type: string
      view:
        type: string
      assetCategory:
        type: string
      usageTerms:
        type: array
        items:
          type: string
      assetHref:
        type: string
        format: uri
      image:
        type: object
        properties:
          style:
            type: string
          width:
            type: integer
          height:
            type: integer
          bgColor:
            type: string
          representation:
            type: string
      video:
        type: object
        properties:
          fileSize:
            type: integer
      model:
        type: object
        properties:
          waist:
            type: string
          chest:
            type: string
          height:
            type: string
          productSize:
            type: string
    required:
      - assetType
      - viewGroup
      - view
      - assetCategory
      - usageTerms
      - assetHref
    example:
      assetType: image
      viewGroup: 3d
      assetCategory: Photography
      usageTerms: B2B Cataloguge
      assetHref: 'http://domain.com/image.jpeg'
      image:
        style: On Model
        width: 2000
        height: 2000
        bgColor: transparent
      model:
        waist: 58
        chest: 97
        height: 197
        productSize: 540
  supermodelIoAdidasProductCatalog:
    title: Catalog
    type: object
    properties:
      catalogueCopy:
        $ref: '#/definitions/supermodelIoAdidasProductCatalogDefinitionsCatalogCopy'
      featureAndBenefits:
        type: array
        items:
          $ref: >-
            #/definitions/supermodelIoAdidasProductCatalogDefinitionsFeatureAndBenefit
    example:
      catalogueCopy: {}
      featureAndBenefits:
        - {}
  supermodelIoAdidasProductColor:
    title: Color
    type: object
    description: Color descriptions are language-dependent
    properties:
      color1:
        $ref: '#/definitions/supermodelIoAdidasProductUtilsCodeDescription'
      color2:
        $ref: '#/definitions/supermodelIoAdidasProductUtilsCodeDescription'
      color3:
        $ref: '#/definitions/supermodelIoAdidasProductUtilsCodeDescription'
      color4:
        $ref: '#/definitions/supermodelIoAdidasProductUtilsCodeDescription'
    example:
      color1:
        code: A0QM
        description: core black
      color2:
        code: A98B
        description: utility black
      color3:
        code: A0QM
        description: core black
      color4:
        code: 01F7
        description: ftwr white
  supermodelIoAdidasProductMarketArticle:
    title: Market Article
    description: Market-specific Article Information
    type: object
    properties:
      articleNumber:
        $ref: >-
          #/definitions/supermodelIoAdidasProductArticle/properties/articleNumber
      modelNumber:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/modelNumber'
      articleDescription:
        $ref: >-
          #/definitions/supermodelIoAdidasProductArticle/properties/articleDescription
      gender:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/gender'
      brand:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/brand'
      productType:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/productType'
      ageGroup:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/ageGroup'
      colorway:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/colorway'
      colors:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/colors'
      skus:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/skus'
      assets:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/assets'
      catalog:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/catalog'
      related:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/related'
      seasonName:
        $ref: >-
          #/definitions/supermodelIoAdidasProductArticleSeason/properties/seasonName
      carryOver:
        $ref: >-
          #/definitions/supermodelIoAdidasProductArticleSeason/properties/carryOver
      retailIntroDate:
        $ref: >-
          #/definitions/supermodelIoAdidasProductArticleSeason/properties/retailIntroDate
      retailExitDate:
        $ref: >-
          #/definitions/supermodelIoAdidasProductArticleSeason/properties/retailExitDate
      prices:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasProductPrice'
  supermodelIoAdidasProductPrice:
    title: Price
    type: object
    properties:
      timePeriodCode:
        type: string
      salesOrg:
        type: string
      distChannel:
        type: string
      priceType:
        type: string
      currency:
        type: string
      validFrom:
        type: string
        format: date-time
      validTo:
        type: string
        format: date-time
      priceValue:
        type: string
      priceUnit:
        type: string
      countryCode:
        type: string
    example:
      timePeriodCode: '71'
      salesOrg: 0681
      distChannel: '01'
      priceType: Act_SalesPrice
      currency: EUR
      validFrom: '2017-01-01'
      validTo: '2017-12-31'
      priceValue: '74,98'
      countryCode: AT
  supermodelIoAdidasProductSKU:
    title: SKU
    type: object
    properties:
      EAN:
        type: string
      UPC:
        type: string
      srcSizeCD3:
        type: string
      srcSizeScale:
        type: string
      srcSizeDescription:
        type: string
      conversionIDs:
        type: array
        items:
          - type: object
            properties:
              localSize:
                type: string
              saleSizeConvID:
                type: string
              saleSizeScale:
                type: string
              saleSizeAbbr:
                type: string
              saleSizeDesc:
                type: string
    example:
      EAN: '4058026055128'
      UPC: '885591427616'
      srcSizeCD3: '380'
      srcSizeScale: T4
      conversionIDs:
        - saleSizeConvID: D
          saleSizeScale: 8C
          saleSizeAbbr: '27'
  supermodelIoAdidasProductApiArticleCatalogHAL:
    title: Article Catalog HAL Representation
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
      - $ref: '#/definitions/supermodelIoAdidasProductCatalog'
    example:
      _links:
        self:
          href: /articles/015110/catalogue
  supermodelIoAdidasProductApiArticleHAL:
    title: Article HAL Representation
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
    properties:
      articleNumber:
        $ref: >-
          #/definitions/supermodelIoAdidasProductArticle/properties/articleNumber
      modelNumber:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/modelNumber'
      articleDescription:
        $ref: >-
          #/definitions/supermodelIoAdidasProductArticle/properties/articleDescription
      gender:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/gender'
      brand:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/brand'
      productType:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/productType'
      ageGroup:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/ageGroup'
      colorway:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/colorway'
      colors:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/colors'
    example:
      _links:
        self:
          href: /articles/015110
        assets:
          href: /articles/015110/assets
        skus:
          href: /articles/015110/skus
        seasons:
          href: /articles/015110/seasons
        catalogue:
          href: /articles/015110/catalogue
        relatedArticles:
          - href: /articles/015111
          - href: /articles/015112
        ecomArticle:
          href: 'https://api.adidas.com/ecom/article/015110'
        availability:
          href: 'https://api.adidas.com/inventory/availability?articlesIds=015110'
      articleNumber: '015110'
      modelNumber: '10034'
      articleDescription: COPA MUNDIAL
      gender:
        code: M
        description: MALE
      brand:
        code: '11'
        description: ADIDAS
      productType:
        code: '104'
        description: FOOTBALL SHOES (FIRM GROUND)
      ageGroup:
        code: A
        description: ADULT
      colorway:
        name: FTWR WHITE/BLACK
        description: BLABAS/GRAFIT/BLABAS
      colors:
        - color1:
            code: A0QM
            description: core black
          color2:
            code: A98B
            description: utility black
          color3:
            code: A0QM
            description: core black
          color4:
            code: 01F7
            description: ftwr white
  supermodelIoAdidasProductApiArticleNotFoundProblemDetail:
    title: Article Not Found Problem
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiProblemDetail'
    example:
      title: Not Found
      detail: Cannot find the requested article
      status: 404
      instance: /articles/1234
  supermodelIoAdidasProductApiArticleSeasonsHAL:
    title: HAL Representation of Collection of Seasons
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
    properties:
      seasonsCount:
        type: number
      seasons:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasProductArticleSeason'
    example:
      _links:
        self:
          href: /articles/015110/seasons
      seasonsCount: 1
      seasons:
        - {}
  supermodelIoAdidasProductApiArticlesHAL:
    title: HAL Representation of Collections of Articles
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
    properties:
      articleCount:
        type: number
    example:
      _links:
        self:
          href: /articles
        next:
          href: /articles?offset=5&limit=5
        first:
          href: /articles?offset=0&limit=5
        last:
          href: /articles?offset=40&limit=5
      articleCount: 1
      _embedded:
        article:
          - {}
  supermodelIoAdidasProductApiAssetsHAL:
    title: HAL Representation of Collection of Assets
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
    properties:
      assetCount:
        type: number
      assets:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasProductAsset'
    example:
      _links:
        self:
          href: /articles/015110/assets
      assetCount: 1
      assets:
        - {}
  supermodelIoAdidasProductApiMarketArticleHAL:
    title: Market Article
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
    properties:
      articleNumber:
        $ref: >-
          #/definitions/supermodelIoAdidasProductMarketArticle/properties/articleNumber
      modelNumber:
        $ref: >-
          #/definitions/supermodelIoAdidasProductMarketArticle/properties/modelNumber
      articleDescription:
        $ref: >-
          #/definitions/supermodelIoAdidasProductMarketArticle/properties/articleDescription
      gender:
        $ref: '#/definitions/supermodelIoAdidasProductMarketArticle/properties/gender'
      brand:
        $ref: '#/definitions/supermodelIoAdidasProductMarketArticle/properties/brand'
      productType:
        $ref: >-
          #/definitions/supermodelIoAdidasProductMarketArticle/properties/productType
      ageGroup:
        $ref: >-
          #/definitions/supermodelIoAdidasProductMarketArticle/properties/ageGroup
      colorway:
        $ref: >-
          #/definitions/supermodelIoAdidasProductMarketArticle/properties/colorway
      colors:
        $ref: '#/definitions/supermodelIoAdidasProductMarketArticle/properties/colors'
      seasonName:
        $ref: >-
          #/definitions/supermodelIoAdidasProductMarketArticle/properties/seasonName
    example:
      _links:
        self:
          href: /markets/A1/articles/015110?season_name=FW17
        skus:
          href: /markets/A1/articles/015110/skus?season_name=FW17
        relatedArticles:
          - href: /markets/A1/articles/015111?season_name=FW17
          - href: /markets/A1/articles/015112?season_name=FW17
        prices:
          href: /markets/A1/articles/015111/prices?season_name=FW17
        assets:
          href: /articles/015110/assets
        catalogue:
          href: /articles/015110/catalogue
      articleNumber: '015110'
      modelNumber: '10034'
      articleDescription: COPA MUNDIAL
      gender:
        code: M
        description: MALE
      brand:
        code: '11'
        description: ADIDAS
      productType:
        code: '104'
        description: FOOTBALL SHOES (FIRM GROUND)
      ageGroup:
        code: A
        description: ADULT
      colorway:
        name: FTWR WHITE/BLACK
        description: BLABAS/GRAFIT/BLABAS
      colors:
        - color1:
            code: A0QM
            description: core black
          color2:
            code: A98B
            description: utility black
          color3:
            code: A0QM
            description: core black
          color4:
            code: 01F7
            description: ftwr white
      seasonName: FW17
      carryOver: false
      retailIntroDate: '2017-06-01'
      retailExitDate: '2017-11-30'
  supermodelIoAdidasProductApiMarketArticlesHAL:
    title: HAL Representation of Collection of Market Articles
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
    properties:
      articleCount:
        type: number
    example:
      _links:
        self:
          href: /markets/A1/articles?season_name=FW17
        next:
          href: /markets/A1/articles?season_name=FW17&offset=5&limit=5
        first:
          href: /markets/A1/articles?season_name=FW17&offset=0&limit=5
        last:
          href: /markets/A1/articles?season_name=FW17&offset=40&limit=5
      _embedded:
        article:
          - {}
      articleCount: 1
  supermodelIoAdidasProductApiMarketHAL:
    title: Market HAL Representation
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
    properties:
      areaCode:
        type: string
      regionCode:
        type: string
    example:
      _links:
        articles:
          href: /markets/A1/articles?season_name=FW17
      areaCode: A1
      regionCode: '50'
  supermodelIoAdidasProductApiMarketSKUsHAL:
    title: HAL Representation of Collection of SKUs
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
      - $ref: '#/definitions/supermodelIoAdidasProductApiSKUsHAL'
    example:
      _links:
        self:
          href: /markets/A1/articles/015110/skus?season_name=FW17
      skuCount: 1
      skus:
        - {}
  supermodelIoAdidasProductApiMarketsHAL:
    title: HAL Representation of Collection of Markets
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
    properties:
      marketsCount:
        type: number
    example:
      _links:
        self:
          href: /markets
      marketsCount: 1
      _embedded:
        market:
          - {}
  supermodelIoAdidasProductApiModelCatalogHAL:
    title: Model Catalog HAL Representation
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
      - $ref: '#/definitions/supermodelIoAdidasProductCatalog'
    example:
      _links:
        self:
          href: /models/10034/catalog
  supermodelIoAdidasProductApiPricesHAL:
    title: HAL Representation of Collection of Prices
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
    properties:
      priceCount:
        type: number
      prices:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasProductPrice'
    example:
      _links:
        self:
          href: /markets/A1/articles/015110/prices?season_name=FW17
      priceCount: 1
      prices:
        - {}
  supermodelIoAdidasProductApiSKUsHAL:
    title: HAL Representation of Collection of SKUs
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
    properties:
      skuCount:
        type: number
      skus:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasProductSKU'
    example:
      _links:
        self:
          href: /articles/015110/skus
      skuCount: 1
      skus:
        - {}
  supermodelIoAdidasProductEcomArticle:
    title: eCom Article
    type: object
    properties:
      articleNumber:
        $ref: >-
          #/definitions/supermodelIoAdidasProductArticle/properties/articleNumber
      modelNumber:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/modelNumber'
      articleDescription:
        $ref: >-
          #/definitions/supermodelIoAdidasProductArticle/properties/articleDescription
      gender:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/gender'
      brand:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/brand'
      productType:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/productType'
  supermodelIoAdidasProductEcomApiArticleHAL:
    title: eCom Article HAL Representation
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
      - $ref: '#/definitions/supermodelIoAdidasProductEcomArticle'
  supermodelIoAdidasProductUtilsCodeDescription:
    title: Code Description Tuple
    description: Helper data structure to hold any code - description pair
    type: object
    properties:
      code:
        type: string
      description:
        type: string
