swagger: '2.0'
info:
  version: '1.0.0'
  title: "[Draft] Reference Data API"
  description: |
    Draft of the Reference Data API

produces:
  - application/hal+json      # Representation message format
  - application/problem+json  # Error message format

schemes:
  - https

securityDefinitions:
   "API Key":
     type: apiKey
     in: header
     name: x-api-key

security:
  - "API Key": []

paths:
  /:
    x-summary: Reference Data API

    get:
      summary: Retrieve Reference Data API Root
      description: Retrieve available top-level actions of the Reference Data API
      responses:
        200:
          description: The root of the API
          schema:
            allOf:
              - $ref: '#/definitions/supermodelIoAdidasApiHAL'
            example:
              _links:
                self:
                  href: /

  /domains:
    x-summary: Reference Data Domains

    get:
      summary: Retrieve Domains
      responses:
        200:
          description: List of domains
          schema:
            $ref: '#/definitions/supermodelIoAdidasApiHAL'

  /domains/{domainId}:
    x-summary: Reference Data Domain
    parameters:
      - $ref: '#/parameters/domainId'

    get:
      summary: Retrieve Domain
      responses:
        200:
          description: One Reference Data Domain
          schema:
            $ref: '#/definitions/supermodelIoAdidasReferenceApiDomainHAL'

  /domains/{domainId}/categories:
    x-summary: Reference Data Categories
    parameters:
      - $ref: '#/parameters/domainId'

    get:
      summary: Retrieve Categories
      responses:
        200:
          description: List of categories
          schema:
            $ref: '#/definitions/supermodelIoAdidasApiHAL'

  /domains/{domainId}/categories/{categoryId}:
    x-summary: Reference Data Category
    x-desscription: Design object
    parameters:
      - $ref: '#/parameters/domainId'
      - $ref: '#/parameters/categoryId'

    get:
      summary: Retrieve Category
      responses:
        200:
          description: One Reference Data Category
          schema:
            $ref: '#/definitions/supermodelIoAdidasApiHAL'

  /domains/{domainId}/categories/{categoryId}/entities:
    x-summary: Category Entities
    parameters:
      - $ref: '#/parameters/domainId'
      - $ref: '#/parameters/categoryId'

    get:
      summary: Retrieve Category Entities
      responses:
        200:
          description: List of entities
          schema:
            $ref: '#/definitions/supermodelIoAdidasApiHAL'

  /domains/{domainId}/categories/{categoryId}/entities/{entityId}:
    x-summary: Category Entity
    x-desscription: Design object instance
    parameters:
      - $ref: '#/parameters/domainId'
      - $ref: '#/parameters/categoryId'
      - $ref: '#/parameters/entityId'

    get:
      summary: Retrieve Category Entity
      responses:
        200:
          description: One Category Entity
          schema:
            $ref: '#/definitions/supermodelIoAdidasApiHAL'            

#
# Parameters Definitions
#
parameters:
  domainId:
    name: domainId
    in: path
    description: Id of a domain
    required: true
    type: string
    x-example: 'product'

  categoryId:
    name: categoryId
    in: path
    description: Id of a category
    required: true
    type: string
    x-example: 'brand'

  entityId:
    name: entityId
    in: path
    description: Code (id) of an entity
    required: true
    type: string
    x-example: '11'  

# DO NOT EDIT
# This definitions section is automatically generated by supermodel.io
#
# http://supermodel.io
# https://github.com/supermodel/supermodel-cli
definitions:
  supermodelIoAdidasApiHALDefinitionsHalLinkObject:
    title: HAL Link Object
    type: object
    properties:
      href:
        type: string
      templated:
        type: boolean
      type:
        type: string
      deprecation:
        type: string
      name:
        type: string
      profile:
        type: string
      title:
        type: string
      hreflang:
        type: string
    required:
      - href
  supermodelIoAdidasApiHALDefinitionsHalCuriesLink:
    title: HAL Curies Link
    allOf:
      - type: object
        properties:
          templated:
            enum:
              - true
        required:
          - templated
      - $ref: '#/definitions/supermodelIoAdidasApiHALDefinitionsHalLinkObject'
  supermodelIoAdidasProductCatalogDefinitionsCatalogCopy:
    title: Catalog Copy
    type: object
    properties:
      acsModelName:
        type: string
      b2cCopy:
        type: string
      b2cCopyShort:
        type: string
      b2bCopy:
        type: string
      b2bCopyShort:
        type: string
      materialComposition:
        type: string
      materialConstruction:
        type: string
      bullets1:
        type: string
      bullets2:
        type: string
      bullets3:
        type: string
      bullets4:
        type: string
      bullets5:
        type: string
      bullets6:
        type: string
      bulletMaterial:
        type: string
    example:
      acsModelName: COPA MUNDIAL
      b2cCopy: >-
        De populairste voetbalschoen ooit, en terecht. De adidas Copa Mundial
        heeft een bovenwerk van rijk leer en een loopzool met dubbele dichtheid
        die al decennia lang de toon zet voor comfort en prestaties op het veld.
      b2cCopyShort: >-
        Entraîne-toi comme les pros avec ce haut de l'équipe de Belgique de
        football.
      b2bCopy: >-
        Hurricanes Training Jersey as worn by the players when training with
        dynamic retro design inspired by the original Super Jersey.Captured with
        shock blue and black colors on climalite fabric with moisture wicking
        properties.
      b2bCopyShort: >-
        Hurricanes Training Jersey as worn by the players when training with
        dynamic retro design inspired by the orginal Super jersey.
      materialComposition: 100% Organic Cotton
      materialConstruction: Single jersey
      bullets1: materiál Climalite odvádí pot a udrží tě vsuchu za všech okolností
      bullets2: Ribbet V-hals
      bullets3: Nackenband
      bullets4: >-
        Επένδυση προστασίας από τον άνεμο στο μπροστινό μέρος. Μανσέτες με
        ανοίγματα για τους αντίχειρες
      bullets5: Woven Belgium crest on chest
      bullets6: >-
        3 bandas en las mangas; logotipo de adidas serigrafiado a la derecha del
        pecho
      bulletMaterial: Maille double 100 % polyester.
  supermodelIoAdidasProductCatalogDefinitionsFeatureAndBenefit:
    title: Feature and Benefit
    type: object
    properties:
      featureAndBenefitCode:
        type: string
      businessCode:
        type: string
      shoePart:
        type: string
      featureName:
        type: string
      featureDescription:
        type: string
      logoName:
        type: string
      logoHref:
        type: string
        format: uri
    example:
      featureAndBenefitCode: '68465468'
      businessCode: BU Young Athlete
      shoePart: Upper
      featureName: Costura à maquina
      featureDescription: >-
        construction nylon/TPU pour un bon toucher de balle et une bonne
        résistance à l'usure.
      logoName: ECO_OrthoLiteLogo
      logoHref: 'http://domain.com/logo.jpeg'
  supermodelIoAdidasApiHAL:
    title: HAL
    description: >-
      JSON Hypertext Application Language. Definition of [HAL message
      format](https://tools.ietf.org/html/draft-kelly-json-hal-08)
    type: object
    properties:
      _links:
        type: object
        additionalProperties: {}
        properties:
          curies: {}
      _embedded:
        type: object
        additionalProperties: {}
  supermodelIoAdidasApiProblemDetail:
    title: Problem Details for HTTP APIs
    description: >-
      Definition of [RFC7807](https://tools.ietf.org/html/rfc7807) problem
      detail
    type: object
    properties:
      type:
        type: string
      title:
        type: string
      status:
        type: number
      detail:
        type: string
      instance:
        type: string
    required:
      - title
      - detail
  supermodelIoAdidasProductArticle:
    title: Article
    type: object
    properties:
      articleNumber:
        type: string
      modelNumber:
        type: string
      articleDescription:
        type: string
      gender:
        $ref: '#/definitions/supermodelIoAdidasProductUtilsCodeDescription'
      brand:
        $ref: '#/definitions/supermodelIoAdidasProductUtilsCodeDescription'
      productType:
        $ref: '#/definitions/supermodelIoAdidasProductUtilsCodeDescription'
      ageGroup:
        $ref: '#/definitions/supermodelIoAdidasProductUtilsCodeDescription'
      colorway:
        type: object
        properties:
          name:
            type: string
          description:
            type: string
      colors:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasProductColor'
      seasons:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasProductArticleSeason'
      skus:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasProductSKU'
      assets:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasProductAsset'
      catalog:
        $ref: '#/definitions/supermodelIoAdidasProductCatalog'
      related:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasProductArticle'
    example:
      articleNumber: '015110'
      modelNumber: '10034'
      articleDescription: COPA MUNDIAL
      gender:
        code: M
        description: MALE
      brand:
        code: '11'
        description: ADIDAS
      productType:
        code: '104'
        description: FOOTBALL SHOES (FIRM GROUND)
      ageGroup:
        code: A
        description: ADULT
      colorway:
        name: FTWR WHITE/BLACK
        description: BLABAS/GRAFIT/BLABAS
      colors:
        - {}
      seasons:
        - {}
      skus:
        - {}
      assets:
        - {}
      catalog: {}
  supermodelIoAdidasProductArticleSeason:
    title: Article Season
    description: Seasonal information about article
    type: object
    properties:
      seasonName:
        type: string
      carryOver:
        type: boolean
      retailIntroDate:
        type: string
        format: date-time
      retailExitDate:
        type: string
        format: date-time
    example:
      seasonName: FW17
      carryOver: false
      retailIntroDate: '2017-06-01'
      retailExitDate: '2017-11-30'
  supermodelIoAdidasProductAsset:
    title: Asset
    description: Digital Asset
    type: object
    properties:
      assetType:
        type: string
        enum:
          - image
          - video
          - other
      viewGroup:
        type: string
      view:
        type: string
      assetCategory:
        type: string
      usageTerms:
        type: array
        items:
          type: string
      assetHref:
        type: string
        format: uri
      image:
        type: object
        properties:
          style:
            type: string
          width:
            type: integer
          height:
            type: integer
          bgColor:
            type: string
          representation:
            type: string
      video:
        type: object
        properties:
          fileSize:
            type: integer
      model:
        type: object
        properties:
          waist:
            type: string
          chest:
            type: string
          height:
            type: string
          productSize:
            type: string
    required:
      - assetType
      - viewGroup
      - view
      - assetCategory
      - usageTerms
      - assetHref
    example:
      assetType: image
      viewGroup: 3d
      assetCategory: Photography
      usageTerms: B2B Cataloguge
      assetHref: 'http://domain.com/image.jpeg'
      image:
        style: On Model
        width: 2000
        height: 2000
        bgColor: transparent
      model:
        waist: 58
        chest: 97
        height: 197
        productSize: 540
  supermodelIoAdidasProductCatalog:
    title: Catalog
    type: object
    properties:
      catalogueCopy:
        $ref: '#/definitions/supermodelIoAdidasProductCatalogDefinitionsCatalogCopy'
      featureAndBenefits:
        type: array
        items:
          $ref: >-
            #/definitions/supermodelIoAdidasProductCatalogDefinitionsFeatureAndBenefit
    example:
      catalogueCopy: {}
      featureAndBenefits:
        - {}
  supermodelIoAdidasProductColor:
    title: Color
    type: object
    description: Color descriptions are language-dependent
    properties:
      color1:
        $ref: '#/definitions/supermodelIoAdidasProductUtilsCodeDescription'
      color2:
        $ref: '#/definitions/supermodelIoAdidasProductUtilsCodeDescription'
      color3:
        $ref: '#/definitions/supermodelIoAdidasProductUtilsCodeDescription'
      color4:
        $ref: '#/definitions/supermodelIoAdidasProductUtilsCodeDescription'
    example:
      color1:
        code: A0QM
        description: core black
      color2:
        code: A98B
        description: utility black
      color3:
        code: A0QM
        description: core black
      color4:
        code: 01F7
        description: ftwr white
  supermodelIoAdidasProductMarketArticle:
    title: Market Article
    description: Market-specific Article Information
    type: object
    properties:
      articleNumber:
        $ref: >-
          #/definitions/supermodelIoAdidasProductArticle/properties/articleNumber
      modelNumber:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/modelNumber'
      articleDescription:
        $ref: >-
          #/definitions/supermodelIoAdidasProductArticle/properties/articleDescription
      gender:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/gender'
      brand:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/brand'
      productType:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/productType'
      ageGroup:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/ageGroup'
      colorway:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/colorway'
      colors:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/colors'
      skus:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/skus'
      assets:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/assets'
      catalog:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/catalog'
      related:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/related'
      seasonName:
        $ref: >-
          #/definitions/supermodelIoAdidasProductArticleSeason/properties/seasonName
      carryOver:
        $ref: >-
          #/definitions/supermodelIoAdidasProductArticleSeason/properties/carryOver
      retailIntroDate:
        $ref: >-
          #/definitions/supermodelIoAdidasProductArticleSeason/properties/retailIntroDate
      retailExitDate:
        $ref: >-
          #/definitions/supermodelIoAdidasProductArticleSeason/properties/retailExitDate
      prices:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasProductPrice'
  supermodelIoAdidasProductPrice:
    title: Price
    type: object
    properties:
      timePeriodCode:
        type: string
      salesOrg:
        type: string
      distChannel:
        type: string
      priceType:
        type: string
      currency:
        type: string
      validFrom:
        type: string
        format: date-time
      validTo:
        type: string
        format: date-time
      priceValue:
        type: string
      priceUnit:
        type: string
      countryCode:
        type: string
    example:
      timePeriodCode: '71'
      salesOrg: 0681
      distChannel: '01'
      priceType: Act_SalesPrice
      currency: EUR
      validFrom: '2017-01-01'
      validTo: '2017-12-31'
      priceValue: '74,98'
      countryCode: AT
  supermodelIoAdidasProductSKU:
    title: SKU
    type: object
    properties:
      EAN:
        type: string
      UPC:
        type: string
      srcSizeCD3:
        type: string
      srcSizeScale:
        type: string
      srcSizeDescription:
        type: string
      conversionIDs:
        type: array
        items:
          type: object
          properties:
            localSize:
              type: string
            saleSizeConvID:
              type: string
            saleSizeScale:
              type: string
            saleSizeAbbr:
              type: string
            saleSizeDesc:
              type: string
    example:
      EAN: '4058026055128'
      UPC: '885591427616'
      srcSizeCD3: '380'
      srcSizeScale: T4
      conversionIDs:
        - saleSizeConvID: D
          saleSizeScale: 8C
          saleSizeAbbr: '27'
  supermodelIoAdidasProductApiArticleCatalogHAL:
    title: Article Catalog HAL Representation
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
      - $ref: '#/definitions/supermodelIoAdidasProductCatalog'
    example:
      _links:
        self:
          href: /articles/015110/catalogue
  supermodelIoAdidasProductApiArticleHAL:
    title: Article HAL Representation
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
    properties:
      articleNumber:
        $ref: >-
          #/definitions/supermodelIoAdidasProductArticle/properties/articleNumber
      modelNumber:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/modelNumber'
      articleDescription:
        $ref: >-
          #/definitions/supermodelIoAdidasProductArticle/properties/articleDescription
      gender:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/gender'
      brand:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/brand'
      productType:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/productType'
      ageGroup:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/ageGroup'
      colorway:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/colorway'
      colors:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/colors'
    example:
      _links:
        self:
          href: /articles/015110
        assets:
          href: /articles/015110/assets
        skus:
          href: /articles/015110/skus
        seasons:
          href: /articles/015110/seasons
        catalogue:
          href: /articles/015110/catalogue
        relatedArticles:
          - href: /articles/015111
          - href: /articles/015112
        ecomArticle:
          href: 'https://api.adidas.com/ecom/article/015110'
        availability:
          href: 'https://api.adidas.com/inventory/availability?articlesIds=015110'
      articleNumber: '015110'
      modelNumber: '10034'
      articleDescription: COPA MUNDIAL
      gender:
        code: M
        description: MALE
      brand:
        code: '11'
        description: ADIDAS
      productType:
        code: '104'
        description: FOOTBALL SHOES (FIRM GROUND)
      ageGroup:
        code: A
        description: ADULT
      colorway:
        name: FTWR WHITE/BLACK
        description: BLABAS/GRAFIT/BLABAS
      colors:
        - color1:
            code: A0QM
            description: core black
          color2:
            code: A98B
            description: utility black
          color3:
            code: A0QM
            description: core black
          color4:
            code: 01F7
            description: ftwr white
  supermodelIoAdidasProductApiArticleNotFoundProblemDetail:
    title: Article Not Found Problem
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiProblemDetail'
    example:
      title: Not Found
      detail: Cannot find the requested article
      status: 404
      instance: /articles/1234
  supermodelIoAdidasProductApiArticleSeasonsHAL:
    title: HAL Representation of Collection of Seasons
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
    properties:
      seasonsCount:
        type: number
      seasons:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasProductArticleSeason'
    example:
      _links:
        self:
          href: /articles/015110/seasons
      seasonsCount: 1
      seasons:
        - {}
  supermodelIoAdidasProductApiArticlesHAL:
    title: HAL Representation of Collections of Articles
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
    properties:
      articleCount:
        type: number
    example:
      _links:
        self:
          href: /articles
        next:
          href: /articles?offset=5&limit=5
        first:
          href: /articles?offset=0&limit=5
        last:
          href: /articles?offset=40&limit=5
      articleCount: 1
      _embedded:
        article:
          - {}
  supermodelIoAdidasProductApiAssetsHAL:
    title: HAL Representation of Collection of Assets
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
    properties:
      assetCount:
        type: number
      assets:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasProductAsset'
    example:
      _links:
        self:
          href: /articles/015110/assets
      assetCount: 1
      assets:
        - {}
  supermodelIoAdidasProductApiMarketArticleHAL:
    title: Market Article
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
    properties:
      articleNumber:
        $ref: >-
          #/definitions/supermodelIoAdidasProductMarketArticle/properties/articleNumber
      modelNumber:
        $ref: >-
          #/definitions/supermodelIoAdidasProductMarketArticle/properties/modelNumber
      articleDescription:
        $ref: >-
          #/definitions/supermodelIoAdidasProductMarketArticle/properties/articleDescription
      gender:
        $ref: '#/definitions/supermodelIoAdidasProductMarketArticle/properties/gender'
      brand:
        $ref: '#/definitions/supermodelIoAdidasProductMarketArticle/properties/brand'
      productType:
        $ref: >-
          #/definitions/supermodelIoAdidasProductMarketArticle/properties/productType
      ageGroup:
        $ref: >-
          #/definitions/supermodelIoAdidasProductMarketArticle/properties/ageGroup
      colorway:
        $ref: >-
          #/definitions/supermodelIoAdidasProductMarketArticle/properties/colorway
      colors:
        $ref: '#/definitions/supermodelIoAdidasProductMarketArticle/properties/colors'
      seasonName:
        $ref: >-
          #/definitions/supermodelIoAdidasProductMarketArticle/properties/seasonName
    example:
      _links:
        self:
          href: /markets/A1/articles/015110?season_name=FW17
        skus:
          href: /markets/A1/articles/015110/skus?season_name=FW17
        relatedArticles:
          - href: /markets/A1/articles/015111?season_name=FW17
          - href: /markets/A1/articles/015112?season_name=FW17
        prices:
          href: /markets/A1/articles/015111/prices?season_name=FW17
        assets:
          href: /articles/015110/assets
        catalogue:
          href: /articles/015110/catalogue
      articleNumber: '015110'
      modelNumber: '10034'
      articleDescription: COPA MUNDIAL
      gender:
        code: M
        description: MALE
      brand:
        code: '11'
        description: ADIDAS
      productType:
        code: '104'
        description: FOOTBALL SHOES (FIRM GROUND)
      ageGroup:
        code: A
        description: ADULT
      colorway:
        name: FTWR WHITE/BLACK
        description: BLABAS/GRAFIT/BLABAS
      colors:
        - color1:
            code: A0QM
            description: core black
          color2:
            code: A98B
            description: utility black
          color3:
            code: A0QM
            description: core black
          color4:
            code: 01F7
            description: ftwr white
      seasonName: FW17
      carryOver: false
      retailIntroDate: '2017-06-01'
      retailExitDate: '2017-11-30'
  supermodelIoAdidasProductApiMarketArticlesHAL:
    title: HAL Representation of Collection of Market Articles
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
    properties:
      articleCount:
        type: number
    example:
      _links:
        self:
          href: /markets/A1/articles?season_name=FW17
        next:
          href: /markets/A1/articles?season_name=FW17&offset=5&limit=5
        first:
          href: /markets/A1/articles?season_name=FW17&offset=0&limit=5
        last:
          href: /markets/A1/articles?season_name=FW17&offset=40&limit=5
      _embedded:
        article:
          - {}
      articleCount: 1
  supermodelIoAdidasProductApiMarketHAL:
    title: Market HAL Representation
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
    properties:
      areaCode:
        type: string
      regionCode:
        type: string
    example:
      _links:
        articles:
          href: /markets/A1/articles?season_name=FW17
      areaCode: A1
      regionCode: '50'
  supermodelIoAdidasProductApiMarketSKUsHAL:
    title: HAL Representation of Collection of SKUs
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
      - $ref: '#/definitions/supermodelIoAdidasProductApiSKUsHAL'
    example:
      _links:
        self:
          href: /markets/A1/articles/015110/skus?season_name=FW17
      skuCount: 1
      skus:
        - {}
  supermodelIoAdidasProductApiMarketsHAL:
    title: HAL Representation of Collection of Markets
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
    properties:
      marketsCount:
        type: number
    example:
      _links:
        self:
          href: /markets
      marketsCount: 1
      _embedded:
        market:
          - {}
  supermodelIoAdidasProductApiModelCatalogHAL:
    title: Model Catalog HAL Representation
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
      - $ref: '#/definitions/supermodelIoAdidasProductCatalog'
    example:
      _links:
        self:
          href: /models/10034/catalog
  supermodelIoAdidasProductApiPricesHAL:
    title: HAL Representation of Collection of Prices
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
    properties:
      priceCount:
        type: number
      prices:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasProductPrice'
    example:
      _links:
        self:
          href: /markets/A1/articles/015110/prices?season_name=FW17
      priceCount: 1
      prices:
        - {}
  supermodelIoAdidasProductApiSKUsHAL:
    title: HAL Representation of Collection of SKUs
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
    properties:
      skuCount:
        type: number
      skus:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasProductSKU'
    example:
      _links:
        self:
          href: /articles/015110/skus
      skuCount: 1
      skus:
        - {}
  supermodelIoAdidasProductEcomArticle:
    title: eCom Article
    type: object
    properties:
      athlete:
        type: string
      clearance:
        type: boolean
      comingSoonSignup:
        type: number
      customizable:
        type: boolean
      age:
        type: string
        example: Infant &amp; Toddler
      brand:
        type: string
        example: Performance
      campaign:
        type: string
        example: >-
          Black Friday;Cyber Monday;After Christmas Sale;End of Season
          Sale;Friends Family;Presidents Day Sale;MLK Jr Day Sale
      color:
        type: string
        example: White
      defaultColor:
        type: string
        example: Copper Metalic / White Chalk / Cardboard
      gender:
        type: string
        example: K
      genderSub:
        type: string
        example: KB
      hastag:
        type: string
      maxQuantity:
        type: string
      productDivision:
        type: string
        example: Accessories
      productLine:
        type: string
        example: Tiro
      productType:
        type: string
      price:
        $ref: '#/definitions/supermodelIoAdidasProductEcomPrice'
      sport:
        type: string
        example: Running
      fitbarPosition:
        type: string
      care:
        $ref: '#/definitions/supermodelIoAdidasProductEcomCare'
      onlineFrom:
        type: string
        description: ISO 8601 Date
        example: '2017-06-21T14:07:17Z'
      onlineTo:
        type: string
        description: ISO 8601 Date
        example: '2017-06-21T14:07:17Z'
      previewTo:
        type: string
        description: ISO 8601 Date
        example: '2017-06-21T14:07:17Z'
      pdp:
        $ref: '#/definitions/supermodelIoAdidasProductEcomPDP'
      flashProduct:
        type: boolean
      hypeProduct:
        type: boolean
      personalizable:
        type: boolean
      preorder:
        type: boolean
      soldout:
        type: boolean
      productFamily:
        type: string
      productFilter:
        type: string
      prodcutLine:
        type: string
      sizeChart:
        type: string
      teams:
        type: string
      template:
        type: string
        description: >-
          The 'Template' is used to identify if the inline or miadidas PDP
          template should be applied in the ecommerce frontend.
      articleNumber:
        $ref: >-
          #/definitions/supermodelIoAdidasProductArticle/properties/articleNumber
      modelNumber:
        $ref: '#/definitions/supermodelIoAdidasProductArticle/properties/modelNumber'
      articleDescription:
        $ref: >-
          #/definitions/supermodelIoAdidasProductArticle/properties/articleDescription
      name:
        type: string
        example: Obuv F/22 Primeknit
      badge:
        $ref: '#/definitions/supermodelIoAdidasProductEcomBadge'
      assets:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasProductAsset'
      colorVariants:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasProductEcomArticle'
      miadidas:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasProductEcomArticle'
      completeLook:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasProductEcomArticle'
  supermodelIoAdidasProductEcomBadge:
    title: Badge
    type: object
    properties:
      style:
        type: string
        enum:
          - new
          - preview
          - preorder
          - sales
          - customizable
          - soldout
        example: new
      description:
        type: string
        example: Nové
  supermodelIoAdidasProductEcomCare:
    title: Care
    description: Care model description
    type: object
    properties:
      bleachingInstruction:
        type: string
      ironInstruction:
        type: string
      dryCleanInstruction:
        type: string
      dryInstruction:
        type: string
      extraCareInstruction:
        type: string
  supermodelIoAdidasProductEcomPDP:
    title: PDP
    description: PDP model description
    type: object
    properties:
      callout:
        type: string
      content:
        type: string
      model:
        type: string
  supermodelIoAdidasProductEcomPrice:
    title: Price
    description: Price model description
    type: object
    properties:
      standardPrice:
        type: number
        example: 3799
      standardPriceWithoutVAT:
        type: number
        example: 3139.67
      currentPrice:
        type: number
        example: 3799
      salesPrice:
        type: number
  supermodelIoAdidasProductEcomApiArticleHAL:
    title: eCom Article HAL Representation
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
    properties:
      age:
        $ref: '#/definitions/supermodelIoAdidasProductEcomArticle/properties/age'
      articleDescription:
        $ref: >-
          #/definitions/supermodelIoAdidasProductEcomArticle/properties/articleDescription
      articleNumber:
        $ref: >-
          #/definitions/supermodelIoAdidasProductEcomArticle/properties/articleNumber
      assets:
        $ref: '#/definitions/supermodelIoAdidasProductEcomArticle/properties/assets'
      athlete:
        $ref: '#/definitions/supermodelIoAdidasProductEcomArticle/properties/athlete'
      badge:
        $ref: '#/definitions/supermodelIoAdidasProductEcomArticle/properties/badge'
      brand:
        $ref: '#/definitions/supermodelIoAdidasProductEcomArticle/properties/brand'
      campaign:
        $ref: '#/definitions/supermodelIoAdidasProductEcomArticle/properties/campaign'
      care:
        $ref: '#/definitions/supermodelIoAdidasProductEcomArticle/properties/care'
      clearance:
        $ref: >-
          #/definitions/supermodelIoAdidasProductEcomArticle/properties/clearance
      color:
        $ref: '#/definitions/supermodelIoAdidasProductEcomArticle/properties/color'
      comingSoonSignup:
        $ref: >-
          #/definitions/supermodelIoAdidasProductEcomArticle/properties/comingSoonSignup
      customizable:
        $ref: >-
          #/definitions/supermodelIoAdidasProductEcomArticle/properties/customizable
      defaultColor:
        $ref: >-
          #/definitions/supermodelIoAdidasProductEcomArticle/properties/defaultColor
      fitbarPosition:
        $ref: >-
          #/definitions/supermodelIoAdidasProductEcomArticle/properties/fitbarPosition
      flashProduct:
        $ref: >-
          #/definitions/supermodelIoAdidasProductEcomArticle/properties/flashProduct
      gender:
        $ref: '#/definitions/supermodelIoAdidasProductEcomArticle/properties/gender'
      genderSub:
        $ref: >-
          #/definitions/supermodelIoAdidasProductEcomArticle/properties/genderSub
      hastag:
        $ref: '#/definitions/supermodelIoAdidasProductEcomArticle/properties/hastag'
      hypeProduct:
        $ref: >-
          #/definitions/supermodelIoAdidasProductEcomArticle/properties/hypeProduct
      maxQuantity:
        $ref: >-
          #/definitions/supermodelIoAdidasProductEcomArticle/properties/maxQuantity
      modelNumber:
        $ref: >-
          #/definitions/supermodelIoAdidasProductEcomArticle/properties/modelNumber
      name:
        $ref: '#/definitions/supermodelIoAdidasProductEcomArticle/properties/name'
      onlineFrom:
        $ref: >-
          #/definitions/supermodelIoAdidasProductEcomArticle/properties/onlineFrom
      onlineTo:
        $ref: '#/definitions/supermodelIoAdidasProductEcomArticle/properties/onlineTo'
      pdp:
        $ref: '#/definitions/supermodelIoAdidasProductEcomArticle/properties/pdp'
      personalizable:
        $ref: >-
          #/definitions/supermodelIoAdidasProductEcomArticle/properties/personalizable
      preorder:
        $ref: '#/definitions/supermodelIoAdidasProductEcomArticle/properties/preorder'
      previewTo:
        $ref: >-
          #/definitions/supermodelIoAdidasProductEcomArticle/properties/previewTo
      price:
        $ref: '#/definitions/supermodelIoAdidasProductEcomArticle/properties/price'
      prodcutLine:
        $ref: >-
          #/definitions/supermodelIoAdidasProductEcomArticle/properties/prodcutLine
      productDivision:
        $ref: >-
          #/definitions/supermodelIoAdidasProductEcomArticle/properties/productDivision
      productFamily:
        $ref: >-
          #/definitions/supermodelIoAdidasProductEcomArticle/properties/productFamily
      productFilter:
        $ref: >-
          #/definitions/supermodelIoAdidasProductEcomArticle/properties/productFilter
      productLine:
        $ref: >-
          #/definitions/supermodelIoAdidasProductEcomArticle/properties/productLine
      productType:
        $ref: >-
          #/definitions/supermodelIoAdidasProductEcomArticle/properties/productType
      sizeChart:
        $ref: >-
          #/definitions/supermodelIoAdidasProductEcomArticle/properties/sizeChart
      soldout:
        $ref: '#/definitions/supermodelIoAdidasProductEcomArticle/properties/soldout'
      sport:
        $ref: '#/definitions/supermodelIoAdidasProductEcomArticle/properties/sport'
      teams:
        $ref: '#/definitions/supermodelIoAdidasProductEcomArticle/properties/teams'
      template:
        $ref: '#/definitions/supermodelIoAdidasProductEcomArticle/properties/template'
    example:
      _links:
        self:
          href: /articles/AH2171?site=cz
      _embedded:
        colorvariant:
          - _links:
              self:
                href: /articles/AH2172?site=cz
          - _links:
              self:
                href: /articles/CQ3025?site=cz
      age: Infant &amp; Toddler
      articleDescription: string
      articleNumber: string
      assets:
        - assetType: image
          viewGroup: 3d
          assetCategory: Photography
          usageTerms: B2B Cataloguge
          assetHref: 'http://domain.com/image.jpeg'
          image:
            style: On Model
            width: 2000
            height: 2000
            bgColor: transparent
          model:
            waist: 58
            chest: 97
            height: 197
            productSize: 540
      athlete: string
      badge:
        style: new
        description: Nové
      brand: Performance
      campaign: >-
        Black Friday;Cyber Monday;After Christmas Sale;End of Season
        Sale;Friends Family;Presidents Day Sale;MLK Jr Day Sale
      care:
        bleachingInstruction: string
        ironInstruction: string
        dryCleanInstruction: string
        dryInstruction: string
        extraCareInstruction: string
      clearance: true
      color: White
      comingSoonSignup: 0
      customizable: true
      defaultColor: Copper Metalic / White Chalk / Cardboard
      fitbarPosition: string
      flashProduct: true
      gender: K
      genderSub: KB
      hastag: string
      hypeProduct: true
      maxQuantity: string
      modelNumber: string
      name: Obuv F/22 Primeknit
      onlineFrom: '2017-06-21T14:07:17Z'
      onlineTo: '2017-06-21T14:07:17Z'
      pdp:
        callout: string
        content: string
        model: string
      personalizable: true
      preorder: true
      previewTo: '2017-06-21T14:07:17Z'
      price:
        standardPrice: 3799
        standardPriceWithoutVAT: 3139.67
        currentPrice: 3799
        salesPrice: 0
      prodcutLine: string
      productDivision: Accessories
      productFamily: string
      productFilter: string
      productLine: Tiro
      productType: string
      sizeChart: string
      soldout: true
      sport: Running
      teams: string
      template: string
  supermodelIoAdidasProductUtilsCodeDescription:
    title: Code Description Tuple
    description: Helper data structure to hold any code - description pair
    type: object
    properties:
      code:
        type: string
      description:
        type: string
  supermodelIoAdidasReferenceCategory:
    title: Category
    description: Category model description
    type: object
    properties:
      name:
        type: string
      domains:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasReferenceDomain'
      parents:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasReferenceCategory'
      children:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasReferenceCategory'
      entities:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasReferenceEntity'
  supermodelIoAdidasReferenceDomain:
    title: Domain
    description: Domain model description
    type: object
    properties:
      name:
        type: string
      categories:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasReferenceCategory'
  supermodelIoAdidasReferenceEntity:
    title: Entity
    description: Entity model description
    type: object
    properties:
      code:
        type: string
      description:
        type: string
      isActive:
        type: boolean
      category:
        $ref: '#/definitions/supermodelIoAdidasReferenceCategory'
      combinations:
        type: array
        items:
          $ref: '#/definitions/supermodelIoAdidasReferenceEntity'
  supermodelIoAdidasReferenceApiCategoryHAL:
    title: CategoryHAL
    description: CategoryHAL model description
    type: object
    properties:
      children:
        $ref: '#/definitions/supermodelIoAdidasReferenceCategory/properties/children'
      domains:
        $ref: '#/definitions/supermodelIoAdidasReferenceCategory/properties/domains'
      entities:
        $ref: '#/definitions/supermodelIoAdidasReferenceCategory/properties/entities'
      name:
        $ref: '#/definitions/supermodelIoAdidasReferenceCategory/properties/name'
      parents:
        $ref: '#/definitions/supermodelIoAdidasReferenceCategory/properties/parents'
  supermodelIoAdidasReferenceApiDomainHAL:
    title: Domain HAL
    description: Domain HAL model description
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
    properties:
      name:
        $ref: '#/definitions/supermodelIoAdidasReferenceDomain/properties/name'
    example:
      _links:
        self:
          href: /domains/product
        categories:
          href: /domains/product/categories
      name: Product
  supermodelIoAdidasReferenceApiEntityHAL:
    title: EntityHAL
    description: EntityHAL model description
    type: object
    properties:
      category:
        $ref: '#/definitions/supermodelIoAdidasReferenceEntity/properties/category'
      code:
        $ref: '#/definitions/supermodelIoAdidasReferenceEntity/properties/code'
      combinations:
        $ref: >-
          #/definitions/supermodelIoAdidasReferenceEntity/properties/combinations
      description:
        $ref: '#/definitions/supermodelIoAdidasReferenceEntity/properties/description'
      isActive:
        $ref: '#/definitions/supermodelIoAdidasReferenceEntity/properties/isActive'
