swagger: '2.0'
info:
  version: '0.1.0'
  title: "[Draft] Store Master Data API"
  description: |
    # Store Master Data API
    Draft of Store Master Data API

produces:
  - application/hal+json      # Representation message format

schemes:
  - https

securityDefinitions:
   "API Key":
     type: apiKey
     in: header
     name: x-api-key

security:
  - "API Key": []

paths:
  /:
    x-summary: API Root

    get:
      summary: Retrieve API Root
      description: The API Root contains the initial set of link relations.
      responses:
        200:
          description: The root of the API
          schema:
            type: object
            allOf:
              - $ref: '#/definitions/supermodelIoAdidasApiHAL'
            example:
              - _links:
                  self:
                    href: /
                  stores:
                    href: /stores
                  storesByGeo:
                    href: /stores-by-geo
                  store:
                    href: /stores/{id}
                    templated: true

  /stores:
    x-summary: Stores

    get:
      summary: List Stores by Country
      description: Retrieves all the stores matching the required country parameter.
      parameters:
        - $ref: '#/parameters/countryCode'
        - $ref: '#/parameters/offset'
        - $ref: '#/parameters/limit'
      responses:
        200:
          description: List of stores
          schema:
            $ref: '#/definitions/supermodelIoAdidasStoreMasterDataApiStoresHAL'

  /stores-by-geo:
    x-summary: Stores by Geolocation

    get:
      summary: List Stores by Geographical Location
      description: Retrieves all the stores in a radius from geographical location
      parameters:
        - $ref: '#/parameters/latitude'
        - $ref: '#/parameters/longitude'
        - $ref: '#/parameters/distance'
        - $ref: '#/parameters/offset'
        - $ref: '#/parameters/limit'
      responses:
        200:
          description: List of stores
          schema:
            $ref: '#/definitions/supermodelIoAdidasStoreMasterDataApiStoresHAL'

  /stores/{storeId}:
    x-summary: Store

    get:
      summary: Retrieve Store Details
      description: Retrieves details about one store.
      parameters:
        - $ref: '#/parameters/storeId'
      responses:
        200:
          description: Store details
          schema:
            $ref: '#/definitions/supermodelIoAdidasStoreMasterDataApiStoreHAL'

        404:
          description: Store not found
          headers:
            Content-Type:
              type: string
              default: application/problem+json
          schema:
            type: object
            # allOf:
            #   - $ref: '#/definitions/supermodelIoAdidasApiProblemDetail'
            example:
              title: Store not found
              detail: Store with given id was not found

  /stores/{storeId}/nearby:
    x-summary: Nearby Stores to a Store

    get:
      summary: Retrieve Stores Nearby
      description: Retrieves stores nearby to the given store.
      parameters:
        - $ref: '#/parameters/storeId'
        - $ref: '#/parameters/distance'
      responses:
        200:
          description: Store details
          schema:
            $ref: '#/definitions/supermodelIoAdidasStoreMasterDataApiStoresHAL'

parameters:
  # adidas API guidelines: Pagination
  offset:
    name: offset
    in: query
    description: >-
      Number of results to skip from the start of the list
    required: false
    type: string
    default: '0'
    x-example: '10'

  # adidas API guidelines: Pagination
  limit:
    name: limit
    in: query
    description: >-
      The maximum number of reusults to return
    required: false
    type: string
    default: '10'
    x-example: '5'

  # adidas API guidelines: Sparse fieldset
  fields:
    name: fields
    in: query
    description: >-
      Comma-separated list of fields to include in the response
    required: false
    type: array
    items:
      type: string
    collectionFormat: csv
    x-example:
      - articleNumber
      - modelNumber

  # adidas API guidelines: Sparse fieldset
  embedded:
    name: embedded
    in: query
    description: >-
      Comma-separated list of resource (relations) to embed in the response
    required: false
    type: array
    items:
      type: string
    collectionFormat: csv
    x-example:
      - prices
      - assets

  latitude:
    name: latitude
    in: query
    description: >-
      Latitude
    required: true
    type: number
    x-example: 33.4112

  longitude:
    name: longitude
    in: query
    description: >-
      Longitude
    required: true
    type: number
    x-example: -119.0713

  countryCode:
    name: countryCode
    in: query
    description: >-
      A short text string code (Alpha-2 Code ISO 3166) specifying the country.
    required: true
    type: string
    x-example: 'DE'

  storeId:
    name: storeId
    in: path
    description: >-
      Unique identifier for the single store record in SSM.
    required: true
    type: string
    x-example: '1234'

  distance:
    name: distance
    in: query
    description: >-
      Distance specifying the radius in km from the location
    required: false
    type: number
    x-example: 50
    default: 100

# DO NOT EDIT
# This definitions section is automatically generated by supermodel.io
#
# http://supermodel.io
# https://github.com/supermodel/supermodel-cli
definitions:
  supermodelIoAdidasStoreMasterDataApiStoreHAL:
    title: Store HAL Representation
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
      - $ref: '#/definitions/supermodelIoAdidasStoreMasterDataCoreStore'
    example:
      _links:
        self:
          href: /stores/1234
        nearby:
          href: /stores/1234/nearby
      identifier:
        ssmId: 123
        bcsCode: abc
        posID: '0001'
      store: {}
      storeClassification: {}
      financialClassification: {}
      location: {}
      operations: {}
      systems: {}
      capabilitiesAndServices: {}
      organization: {}
      events: {}
      consumer: {}
  supermodelIoAdidasStoreMasterDataApiStoresHAL:
    title: Stores HAL Representation
    type: object
    allOf:
      - $ref: '#/definitions/supermodelIoAdidasApiHAL'
      - $ref: '#/definitions/supermodelIoAdidasStoreMasterDataCoreStore'
    example:
      _links:
        self:
          href: /stores?country=DE
        next:
          href: /stores?country=DE&offset=10
        last:
          href: /stores?country=DE&offset=80
      numberOfResults: 87
      _embedded:
        store:
          - _links:
              self:
                href: /stores/1234
              someStoreInfo: Store 1
          - _links:
              self:
                href: /stores/1235
              someStoreInfo: Store 2
          - _links:
              self:
                href: /stores/1236
              someStoreInfo: Store 3
  supermodelIoAdidasStoreMasterDataCoreStore:
    title: Store
    type: object
  supermodelIoAdidasApiHAL:
    title: HAL
    description: >-
      JSON Hypertext Application Language. Definition of [HAL message
      format](https://tools.ietf.org/html/draft-kelly-json-hal-08)
    type: object
    properties:
      _links:
        type: object
        additionalProperties:
          allOf:
            - $ref: '#/definitions/supermodelIoAdidasApiHALDefinitionsHalLinkObject'
            - type: array
              items:
                $ref: '#/definitions/supermodelIoAdidasApiHALDefinitionsHalLinkObject'
        properties:
          curies:
            allOf:
              - $ref: '#/definitions/supermodelIoAdidasApiHALDefinitionsHalCuriesLink'
              - type: array
                items:
                  $ref: >-
                    #/definitions/supermodelIoAdidasApiHALDefinitionsHalCuriesLink
      _embedded:
        type: object
        additionalProperties:
          allOf:
            - $ref: '#/definitions/supermodelIoAdidasApiHAL'
            - type: array
              items:
                $ref: '#/definitions/supermodelIoAdidasApiHAL'
  supermodelIoAdidasApiHALDefinitionsHalLinkObject:
    title: HAL Link Object
    type: object
    properties:
      href:
        type: string
      templated:
        type: boolean
      type:
        type: string
      deprecation:
        type: string
      name:
        type: string
      profile:
        type: string
      title:
        type: string
      hreflang:
        type: string
    required:
      - href
  supermodelIoAdidasApiHALDefinitionsHalCuriesLink:
    title: HAL Curies Link
    allOf:
      - type: object
        properties:
          templated:
            enum:
              - true
        required:
          - templated
      - $ref: '#/definitions/supermodelIoAdidasApiHALDefinitionsHalLinkObject'

